### ISSUE TITLE
Request for further documentation

### ISSUE THREAD

**Issue by aiavci** [vanniktech/espresso-utils#43]
**Version**
v0.2.0

**Details**
The documentation on this library has much room for improvement. I'm getting an error when using this library but I'm not even if I'm using it the way it was intended.

**Bug Details**
_When I call:_
`onView(withChild(withTextViewDrawableLeft(R.drawable.example)))
                .check(matches(isDisplayed()))`

_I get:_
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
at com.vanniktech.espresso.core.utils.Utils.drawableMatches(Utils.java:46)`

**Comment by vanniktech** [comment]
Update to the latest version and the documentation is in the README.

**Comment by vanniktech** [comment]
The image you're checking against has no drawable set. Are you missing javadoc?

**Comment by aiavci** [comment]
To my understanding the use case is to validate against specific views instead of the method actually finding the drawable for you. This wasn't clear through the documentation.
_i.e. Instead of calling:_
```
onView(withId(R.id.example_view))
                .check(matches(withTextViewDrawableLeft(R.drawable.example))))
```

I should have called:
`onView(withId(R.id.example_view)).check(matches(withTextViewDrawableLeft(R.drawable.example)))`

**Comment by vanniktech** [comment]
Oh okay got it. I'll do some more javadoc and also adjust the README.

**Comment by vanniktech** [comment]
I hope you like the improvements. Thanks for the suggestion.
